const formFields = [
  {
    id: 'id',
    name: 'App id',
    type: 'string',
    required: true,
    helpText: 'UUID (Auto-generated by editor for new manifests)',
    readOnly: true
  },
  {
    id: 'manifestVersion',
    name: 'Manifest version',
    type: 'string',
    valuespace: 'number',
    required: true,
    helpText: 'Version number is automatically updated by the editor.',
    readOnly: true
  },
  {
    id: 'displayName',
    name: 'Display Name',
    type: 'string',
    required: true,
    helpText: 'Name of integration, as it will appear on Control Hub',
  },
  {
    id: 'vendor',
    name: 'Vendor',
    type: 'string',
    required: true,
    helpText: 'Company that created the integration'
  },
  {
    id: 'email',
    name: 'E-mail',
    type: 'string',
    valuespace: 'email',
    required: true,
  },
  {
    id: 'description',
    name: 'Description',
    type: 'text',
    required: true,
    helpText: 'A description of what the integration does and what value it will provide to the customer'
  },
  {
    id: 'availability',
    name: 'Availability',
    type: 'select',
    values: ['global', 'org_private'],
    required: true,
    helpText: 'Whether the integration will be available only in your org, or to all customers.'
  },
  {
    id: 'descriptionUrl',
    name: 'Description URL',
    type: 'string',
    helpText: 'URL to more details about the integration '
  },
  {
    id: 'tocUrl',
    name: 'Terms URL',
    type: 'string',
    helpText: 'URL to terms and conditions',
    required: false, // this.config.availability === 'global',
  }
];